# G2++ Interest Rate Model


## 1. Introduction

The G2++ model is a two-factor Gaussian short-rate model used to describe the dynamics of interest rates and to price interest-rate derivatives.

In this exercise, we will study the model, derive its main properties, and calibrate its parameters to market swaption volatilities.

## 2. Model Setup

The short rate is modeled as:



$$\large r_t = x_t + y_t + \varphi(t)$$



It is decomposed into two stochastic factors, $x_t$ and $y_t$, and a deterministic function $\varphi(t)$.

<br><br>

### 2.1 Mathematical Framework

<br>

##### **Probability space & risk-neutral measure**

We work on a filtered probability space

$
(\Omega,\mathcal{F},(\mathcal{F}_t)_{t\geq0},\mathbb{Q}),
$
where $\mathbb{Q}$ denotes the risk-neutral measure, $\mathcal{F}$ is the underlying sigma-algebra, and $(\mathcal{F}_t)_{t\geq0}$ represents the filtration of the information available up to time $t$.

<br>

##### **Brownian motions and correlation**

We consider two Brownian motions $(W_t^1)_{t \geq 0}$ and $(W_t^2))_{t \geq 0}$, which are correlated with instantaneous correlation $\rho$:

$
dW_t^1\,dW_t^2 = \rho\,dt,
$
with
$
 \rho\in[-1,1].
$

<br>

##### **Definition of the two stochastic factors**

The two stochastic factors are modeled as Ornstein–Uhlenbeck processes:

$dx_t = -a x_t\,dt + \sigma\,dW_t^1,$

$dy_t = -b y_t\,dt + \eta\,dW_t^2,$

Where $a,b>0$ are the mean-reversion parameters and $\sigma,\eta>0$ are the volatility parameters. The processes start from the initial values $x_0$ and $y_0$, respectively. The function $\varphi(t)$ is deterministic and is chosen to fit the initial term structure of interest rates.

<br><br>

### 2.2 Analytical Properties of the Stochastic Factors

**Closed-form solution of $x_t$ and $y_t$**

To derive the main analytical properties of the model, we first solve the dynamics of each stochastic factor separately. Recall the Ornstein–Uhlenbeck process:

$$
dx_t = -a x_t\,dt + \sigma\,dW_t^1
$$

Rewriting the dynamics of $x_t$, we have:

$$ 
d(e^{at}x_t)= \sigma\,e^{at}dW_t^1
$$

<br>

Integrating from $0$ to $t$ gives:

<br>

$$
e^{at}x_t=x_0 + \sigma \int_0^t e^{as}dW_s^1
$$

And then:

<br>

$$
\boxed{x_t=x_0 e^{-at} + \sigma \int_0^t e^{-a(t-s)}dW_s^1}
$$

<br>

The quantity of interest is the time integral of $x_t$. Integrating the closed-form solution from $0$ to $T$ gives:

<br>

$$
\int_0^T x_t dt = x_0(\frac{1-e^{-aT}}{a}) + \sigma \int^T_0\left(\int^t_0 e^{-a(t-s)}dW_s^1\right)dt
$$

<br>

Using the stochastic Fubini theorem, we can interchange the Lebesgue integral and the stochastic integral:

<br>

$$
\begin{aligned}
\int_0^T x_t dt &= x_0(\frac{1-e^{-aT}}{a}) + \sigma \int^T_0\left(\int^T_s e^{-a(t-s)}dt\right)dW_s^1\\
                &= x_0(\frac{1-e^{-aT}}{a}) + \sigma \int^T_0\left(\frac{1-e^{-a(T-s)}}{a}\right)dW_s^1

\end{aligned}
$$

<br>

The time integral of $x_t$ is Gaussian, as it is the sum of a deterministic term and a Gaussian stochastic integral. We can therefore fully characterize its distribution through its mean and variance.
We can now compute the expectation and variance of the time integral:

$$
\mathbb{E}\left[\int_0^T x_t\,dt\right]
=
x_0\frac{1-e^{-aT}}{a},
$$

and

$$
\operatorname{Var}\left(\int_0^T x_t\,dt\right)
=
\frac{\sigma^2}{a^2}
\int_0^T
\left(1-e^{-a(T-s)}\right)^2ds.
$$

<br>

The covariance between the two stochastic components is given by:

$$
\boxed{
\operatorname{Cov}\left(
\int_0^T x_t\,dt,
\int_0^T y_t\,dt
\right)
=
\frac{\sigma\eta\rho}{ab}
\int_0^T
\left(1-e^{-a(T-s)}\right)
\left(1-e^{-b(T-s)}\right)\,ds
}
$$

<br>

$$
\boxed{
\operatorname{Cov}\left(
\int_0^T x_t\,dt,
\int_0^T y_t\,dt
\right)
=
\frac{\sigma\eta\rho}{ab}
\left[
T
-\frac{1-e^{-aT}}{a}
-\frac{1-e^{-bT}}{b}
+\frac{1-e^{-(a+b)T}}{a+b}
\right]
}
$$

<br>

The pair $(W_t^1,W_t^2)$ is jointly Gaussian. Since $x_t$ and $y_t$ are linear functionals of these Brownian motions, their sum is Gaussian. Therefore, the integrated short rate is also Gaussian:

<br>

$$
\int_0^T r_t dt \sim \mathcal{N} (\mu_T , \nu_T)
$$

We can therefore write:

$$
\int_0^T r_t\,dt \sim \mathcal{N}(\mu_T,\nu_T),
$$

where

$$
\boxed{
\mu_T
=
\int_0^T \varphi(t)\,dt
+
x_0\frac{1-e^{-aT}}{a}
+
y_0\frac{1-e^{-bT}}{b}
}
$$

and

$$
\boxed{
\begin{aligned}
\nu_T
={}&
\frac{\sigma^2}{a^2}
\int_0^T
\left(1-e^{-a(T-s)}\right)^2\,ds\\
&+
\frac{\eta^2}{b^2}
\int_0^T
\left(1-e^{-b(T-s)}\right)^2\,ds\\
&+
\frac{2\sigma\eta\rho}{ab}
\int_0^T
\left(1-e^{-a(T-s)}\right)
\left(1-e^{-b(T-s)}\right)\,ds.
\end{aligned}
}
$$

<br>

Under the risk-neutral measure, our objective is to determine the model-implied zero-coupon bond price for a maturity $T$. Since the bond pays one unit at maturity, its time-$0$ price is given by the expected value of the discounted payoff:

<br>

$$
\boxed{
P(0,T)
=
\mathbb{E}^{\mathbb{Q}}
\left[
e^{-\int_0^T r_t\,dt}
\right]
}
$$

<br>

Since we have shown that the integrated short rate is Gaussian, we can evaluate this expectation in closed form using the moment-generating function of a Gaussian random variable.
For a Gaussian random variable $Z\sim\mathcal{N}(\mu,\nu)$, the moment-generating function provides a convenient way to evaluate the exponential expectation appearing in the zero-coupon bond price. It is given by:

$$
\mathbb{E}\left[e^{uZ}\right]
=
e^{u\mu+\frac{1}{2}u^2\nu}.
$$

Applying this result to our case, we set $Z=\int_0^T r_t\,dt$, $u=-1$, $\mu=\mu_T$ and $\nu=\nu_T$. Therefore, the zero-coupon bond price can be written as:

$$
\begin{aligned}
P(0,T)
&=
\mathbb{E}^{\mathbb{Q}}
\left[
e^{-\int_0^T r_t\,dt}
\right]\\
&=
e^{-\mu_T+\frac{1}{2}\nu_T}.
\end{aligned}
$$



The analytical expression obtained above gives the model-implied zero-coupon bond price. We now use this result to calibrate the deterministic function $\varphi(t)$ so that the model exactly reproduces the observed initial term structure.

### 2.3 Calibration

The analytical bond price derived above provides the basis for calibrating the model parameters to market data. The calibration procedure aims to determine the parameters governing the dynamics of the two stochastic factors, their correlation, and the deterministic shift required to reproduce the observed term structure. We first focus on the deterministic shift $\varphi(t)$, which allows the model to match the initial zero-coupon bond curve once the stochastic-factor parameters are fixed. From the analytical expression obtained above, we can derive $\varphi(T)$ explicitly.

Starting from the model-implied zero-coupon bond price,

$$
P(0,T)=e^{-\mu_T+\frac{1}{2}\nu_T},
$$

we take the logarithm and differentiate with respect to the maturity $T$. Using the expression of $\mu_T$, we obtain:

$$
-\frac{\partial}{\partial T}\log P(0,T)
=
\varphi(T)
+x_0e^{-aT}
+y_0e^{-bT}
-\frac{1}{2}\frac{d\nu_T}{dT}.
$$

Since the instantaneous forward rate is defined by

$$
f^M(0,T)
=
-\frac{\partial}{\partial T}\log P^M(0,T),
$$

the deterministic shift required to match the market curve is therefore:

$$
\boxed{
\varphi(T)
=
f^M(0,T)
-x_0e^{-aT}
-y_0e^{-bT}
+\frac{1}{2}\frac{d\nu_T}{dT}
}
$$

In practice, the market curve is available at discrete maturities, so an interpolation scheme is required to obtain a continuous term structure and its associated instantaneous forward rate.

The deterministic shift $\varphi(t)$ allows the model to reproduce the initial zero-coupon curve for any given set of stochastic parameters. We can therefore focus on calibrating the five parameters governing the dynamics of the two stochastic factors,

$$
\theta=(a,b,\sigma,\eta,\rho).
$$

These parameters are calibrated using the market quotes of European ATM swaptions. Since swaption market quotes are conventionally expressed in terms of implied volatilities, we need to establish the link between the G2++ model price and the corresponding market volatility before defining the calibration objective.

For a given set of parameters $\theta$, the G2++ model provides a price for each swaption $i$:

$$
V_i^{G2++}(\theta;P^M(0,.)).
$$

To compare this model price with the market quote, we use the Black-76 swaption pricing formula. For a given implied volatility $\sigma_i$, the Black price can be written as

$$
V_i^{Black}(\sigma_i)
=
A_i
\left[
F_i N(d_1)-K_i N(d_2)
\right],
$$

where

$$
d_1
=
\frac{\ln(F_i/K_i)+\frac{1}{2}\sigma_i^2T_i}
{\sigma_i\sqrt{T_i}},
\qquad
d_2=d_1-\sigma_i\sqrt{T_i}.
$$

The market provides, for each swaption $i$, a quoted Black implied volatility $\sigma_i^{\mathrm{Mkt}}$. To compare the G2++ model with these market quotes, we first compute the theoretical price of the swaption under G2++ and then express this price in terms of an equivalent Black implied volatility.
The corresponding G2++ implied volatility, denoted by $\sigma_i^{\mathrm{G2++}}(\theta)$, is defined as the Black implied volatility that reproduces this model price. It is therefore obtained as the solution of

$$
V_i^{\mathrm{Black}}\left(\sigma_i^{\mathrm{G2++}}(\theta)\right)
=
V_i^{\mathrm{G2++}}\left(\theta;P^{\mathrm{Mkt}}(0,\cdot)\right).
$$

This allows the G2++ model and the market to be expressed in the same volatility convention. The calibration therefore aims to find the set of stochastic parameters for which the G2++ implied volatilities are as close as possible to the corresponding market implied volatilities:

$$
\sigma_i^{\mathrm{G2++}}(\theta)
\quad \text{and} \quad
\sigma_i^{\mathrm{Mkt}}.
$$

The calibrated parameters are obtained by minimizing the weighted squared difference between the model and market implied volatilities:

$$
\boxed{
\theta^{*}
=
\underset{\theta}{\operatorname{argmin}}
\sum_{i=1}^{N}
w_i
\left(
\sigma_i^{\mathrm{G2++}}(\theta)
-
\sigma_i^{\mathrm{Mkt}}
\right)^2
}
$$

where $w_i$ denotes the weight assigned to swaption $i$.

For each candidate set of parameters $\theta$, the deterministic shift $\varphi(t)$ is determined from the initial market zero-coupon curve and the corresponding stochastic parameters. The G2++ swaption prices can then be computed and converted into implied volatilities, which are compared with the market quotes throughout the calibration procedure.

<br><br>

## 3. Implementation

The analytical framework developed above provides the theoretical basis for the G2++ model and its calibration. We now turn to its implementation using QuantLib, with the objective of calibrating the stochastic parameters to market swaption quotes and reproducing the calibration results reported by Brigo and Mercurio.

The implementation is organized into three main steps: first, the construction of the market data and yield curve; second, the construction and calibration of the G2++ model; and finally, the calculation of model-implied volatilities and their comparison with market quotes.

### 3.1 Market Data

The first step consists in constructing the market inputs required by the G2++ model. In particular, the model needs the initial zero-coupon curve to determine the deterministic shift and a set of swaption market quotes to calibrate its stochastic parameters.

For the calibration, we consider European at-the-money swaptions across different maturity and tenor pillars. The corresponding market quotes are expressed as Black implied volatilities, which will later be used as the reference for the calibration of the G2++ parameters.

The following cells construct these market inputs using QuantLib. The zero-coupon curve will provide the initial term structure, while the swaption quotes will define the set of calibration instruments used to estimate $\theta = (a,b,\sigma,\eta,\rho)$.

In [1]:
import QuantLib as ql
import pandas as pd

print(ql.__version__)

1.43

In [2]:
#QuantLib class date
today = ql.Date(13, 2, 2001)

#Set the fixing date
ql.Settings.instance().evaluationDate = today

Having fixed the evaluation date, the next step is to introduce the initial zero-coupon curve used by the model. This curve represents the market term structure observed at the calibration date and will later be used to determine the deterministic shift $\varphi(t)$.
We use the zero-coupon curve reported in the Brigo and Mercurio example, based on EURO market data observed on 13 February 2001. The curve provides the initial term structure $P^{M}(0,T)$ required by the G2++ model.
We first define the market maturities and their corresponding zero-coupon bond prices. These quantities will then be passed to QuantLib to construct the term structure used throughout the calibration. Following the setup considered by Brigo and Mercurio, we consider seven swaption expiry maturities of 1, 2, 3, 4, 5, 7 and 10 years. For each expiry, the underlying swap tenor ranges from 1 to 10 years, giving a total of $7 \times 10 = 70$ calibration swaptions.

In [3]:
# Swaption expiry maturities (in years)
option_maturities = [1, 2, 3, 4, 5, 7, 10]

The next step is to construct the initial zero-coupon curve corresponding to the calibration date. The curve provides the market discount factors \(P^{M}(0,T)\) required to define the initial term structure and, subsequently, the deterministic shift of the G2++ model.

The zero-coupon curve used in the calibration is approximated from the term structure of discount factors reported by Brigo and Mercurio for the EUR market on February 13, 2001 at 5 p.m. Since the curve is provided graphically rather than as a numerical dataset, the discount factors are extracted approximately at the required maturities and used to construct the initial term structure in QuantLib.

In standard market practice, zero-coupon discount factors are typically obtained by bootstrapping market instruments such as swaps. However, this additional step is not required here, since the reference zero-coupon curve is directly available from the Brigo and Mercurio example.

The resulting curve is then interpolated where necessary in order to provide $P^{M}(0,T)$ for the maturities required by the G2++ calibration.





<img src="ZC_curve_13_02_2001.png" width="1000">

In [9]:
# Zero-coupon curve maturities
curve_maturities = [today + ql.Period(i, ql.Years) for i in range(0, 22)]

# Placeholder discount factors
discount_factors = [
    1.0,   # 0Y
    0.953, # 1Y
    0.912, #2Y
    0.871, #3Y
    0.835, # 4Y
    0.788, #5Y
    0.747, #6Y
    0.706, # 7Y
    0.665, # 8Y
    0.631, # 9Y
    0.5965, #10Y
    0.562, #11Y
    0.527, # 12Y
    0.497, # 13Y
    0.465, #14Y
    0.441, # 15Y
    0.415, # 16Y
    0.389,  # 17Y
    0.367, #18Y
    0.344, #19Y
    0.322, #20Y
    0.306, #21Y
]

curve = ql.DiscountCurve(
    curve_maturities,
    discount_factors,
    ql.Actual365Fixed()
)

curve_handle = ql.YieldTermStructureHandle(curve)

Once the initial zero-coupon curve has been constructed, it is passed to the G2++ model through a YieldTermStructureHandle. The handle does not modify the curve; it simply provides a QuantLib interface through which the model can access the market term structure.

We then specify initial values for the five stochastic parameters of the G2++ model,

$$
(a,b,\sigma,\eta,\rho),
$$

which are used as starting values for the subsequent calibration.

The model is then instantiated in QuantLib using these initial parameters and the market yield curve. At this stage, the model is not yet calibrated: the parameter values are only initial guesses that will later be adjusted to reproduce the observed market swaption volatilities.

In [10]:
curve_handle = ql.YieldTermStructureHandle(curve)

a = 0.1
sigma = 0.01
b = 0.3
eta = 0.01
rho = -0.7

g2 = ql.G2(curve_handle,a,sigma,b,eta,rho)

The calibration is based on the 70 ATM European swaptions reported by Brigo and Mercurio, obtained from the seven expiry maturities and ten underlying swap tenors considered in the exercise.

For each market quote, we need to create the corresponding financial instrument in QuantLib so that it can subsequently be valued using the G2++ model. The swaption is therefore not a separate product specific to the model: it is the same market instrument, which will be priced under the G2++ dynamics.

To facilitate this process, QuantLib provides the SwaptionHelper class, which encapsulates the main information required for calibration, including the swaption's expiry, underlying swap tenor, market volatility and relevant conventions. Each SwaptionHelper therefore represents one of the market swaptions used in the calibration.

Once the 70 helpers have been created, we assign the G2++ pricing engine to them. QuantLib can then compute the model price of each market swaption for a given set of G2++ parameters. These model prices are subsequently used during the calibration to adjust the five stochastic parameters $(a,b,\sigma,\eta,\rho)$ so that the model reproduces the observed market volatilities as closely as possible.

The overall logic is therefore:

$$
\text{Market quotes}
\rightarrow
\text{SwaptionHelpers}
\rightarrow
\text{G2++ pricing}
\rightarrow
\text{Calibration}.
$$

In [11]:
# Underlying swap tenors
swap_tenors = list(range(1, 11))

# ATM market swaption volatilities
swaption_vols = [
                [0.1870, 0.1529, 0.1395, 0.1327, 0.1276, 0.1231, 0.1190, 0.1154, 0.1120, 0.1085],  # 1Y
                [0.1603, 0.1427, 0.1348, 0.1295, 0.1251, 0.1210, 0.1174, 0.1139, 0.1103, 0.1068],  # 2Y
                [0.1509, 0.1376, 0.1307, 0.1258, 0.1216, 0.1180, 0.1146, 0.1109, 0.1073, 0.1041],  # 3Y
                [0.1422, 0.1311, 0.1252, 0.1210, 0.1175, 0.1142, 0.1106, 0.1069, 0.1037, 0.1005],  # 4Y
                [0.1335, 0.1247, 0.1199, 0.1165, 0.1134, 0.1098, 0.1062, 0.1030, 0.0998, 0.0968],  # 5Y
                [0.1218, 0.1161, 0.1124, 0.1087, 0.1050, 0.1018, 0.0986, 0.0954, 0.0928, 0.0902],  # 7Y
                [0.1090, 0.1029, 0.0997, 0.0965, 0.0934, 0.0909, 0.0884, 0.0858, 0.0833, 0.0809],  # 10Y
                ]

for i, maturity in enumerate(option_maturities):
    for j, tenor in enumerate(swap_tenors):

        market_vol = swaption_vols[i][j]

        volatility = ql.QuoteHandle(
            ql.SimpleQuote(market_vol)
        )
index = ql.Euribor6M(curve_handle)
fixed_leg_day_count = ql.Actual360()
floating_leg_day_count = ql.Actual360()

fixed_leg_frequency = ql.Period(1, ql.Years) #fréquence de coupon
swap_tenors = list(range(1, 11))

swaption_helpers = []

for i, maturity in enumerate(option_maturities):
    for j, tenor in enumerate(swap_tenors):

        market_vol = swaption_vols[i][j]

        volatility = ql.QuoteHandle(
            ql.SimpleQuote(market_vol)
        )

        helper = ql.SwaptionHelper(
            ql.Period(maturity, ql.Years),
            ql.Period(tenor, ql.Years),
            volatility,
            index,
            fixed_leg_frequency,
            fixed_leg_day_count,
            floating_leg_day_count,
            curve_handle,
            ql.BlackCalibrationHelper.PriceError
        )

        swaption_helpers.append(helper)


g2_engine = ql.G2SwaptionEngine(
                                g2,
                                7.0,
                                64
                                )

for helper in swaption_helpers:
    helper.setPricingEngine(g2_engine)

optimization_method = ql.LevenbergMarquardt()

end_criteria = ql.EndCriteria(
                                1000,   # maxIterations
                                100,    # maxStationaryStateIterations
                                1e-8,   # rootEpsilon
                                1e-8,   # functionEpsilon
                                1e-8    # gradientNormEpsilon
                            )




    
g2.calibrate(
    swaption_helpers,
    optimization_method,
    end_criteria
)


model_vols = []

for helper in swaption_helpers:
    model_price = helper.modelValue()

    model_vol = helper.impliedVolatility(
        model_price,
        1e-8,
        1000,
        0.0,
        4.0
    )

    model_vols.append(model_vol)

model_vols_matrix = [
    model_vols[i * 10:(i + 1) * 10]
    for i in range(7)
]

model_vols_df = pd.DataFrame(
    model_vols_matrix,
    index=option_maturities,
    columns=swap_tenors
)

vol_error_df = model_vols_df - pd.DataFrame(
    swaption_vols,
    index=option_maturities,
    columns=swap_tenors
)
vol_error_pct_df = (
    vol_error_df
    / pd.DataFrame(
        swaption_vols,
        index=option_maturities,
        columns=swap_tenors
    )
    * 100
)



model_vols_df

,1,2,3,4,5,6,7,8,9,10
1,0.159708,0.146194,0.146945,0.133891,0.128603,0.122832,0.116817,0.113904,0.110025,0.105716
2,0.153647,0.155736,0.138606,0.133333,0.127530,0.121448,0.118760,0.114889,0.110490,0.105638
3,0.169798,0.138911,0.133649,0.127942,0.121921,0.119704,0.115986,0.111599,0.106677,0.103444
4,0.122591,0.124611,0.121719,0.117299,0.116515,0.113595,0.109687,0.105037,0.102094,0.097986
5,0.132345,0.125309,0.119202,0.118741,0.115563,0.111262,0.106181,0.103072,0.098672,0.097049
7,0.114602,0.118702,0.115747,0.111109,0.105497,0.102564,0.097848,0.096552,0.093645,0.090339
10,0.107346,0.100319,0.099432,0.094553,0.094829,0.092133,0.088686,0.086735,0.083797,0.080998

In [12]:
vol_error_pct_df

,1,2,3,4,5,6,7,8,9,10
1,-14.594864,-4.385948,5.336967,0.897595,0.786118,-0.217529,-1.834167,-1.296365,-1.763495,-2.565721
2,-4.150625,9.135343,2.823285,2.960189,1.942191,0.370168,1.158027,0.868394,0.172082,-1.087556
3,12.523564,0.953115,2.256150,1.702487,0.264184,1.444336,1.209335,0.629899,-0.580609,-0.630468
4,-13.789706,-4.949837,-2.780597,-3.058982,-0.838527,-0.529369,-0.825557,-1.742632,-1.548265,-2.501019
5,-0.865081,0.488316,-0.582364,1.923844,1.907055,1.331454,-0.017514,0.069546,-1.129795,0.257625
7,-5.909992,2.241597,2.977768,2.216246,0.472949,0.750175,-0.762559,1.207159,0.911005,0.153815
10,-1.517844,-2.507828,-0.269303,-2.017685,1.530068,1.356716,0.323383,1.090267,0.596884,0.120663

In [13]:
print(g2.params())

[ 0.0754283; 0.0102205; 0.856329; 0.0162867; -0.64174 ]

## 4. Conclusion

This exercise implemented the calibration of a two-factor Gaussian short-rate model (G2++) using QuantLib and ATM European swaption market quotes from Brigo and Mercurio.

The initial EUR zero-coupon curve was reconstructed approximately from the discount-factor curve reported by Brigo and Mercurio for February 13, 2001. Since the original numerical curve was not directly available, the corresponding discount factors were extracted from the published graph and interpolated where required. This represents the main source of uncertainty in the market inputs used for the calibration.

The G2++ model was then implemented in QuantLib using the reconstructed yield curve, and the 70 swaption instruments were represented through SwaptionHelper objects. A single set of five model parameters ((a,b,\sigma,\eta,\rho)) was calibrated simultaneously to the complete swaption volatility surface.

The calibration reproduces the general structure of the market volatility surface reasonably well, with larger discrepancies mainly concentrated on short-expiry instruments. The calibrated parameters are economically plausible for the mean-reversion parameters, while the correlation is very close to its lower bound, suggesting that the model relies on a strongly negatively correlated factor structure to fit the market data. This may partly reflect the approximate reconstruction of the historical yield curve and the uncertainty surrounding the exact market conventions used in the original calibration.

Overall, the implementation demonstrates how the theoretical G2++ framework can be translated into a practical calibration workflow using an existing quantitative finance library, while highlighting the importance of the quality and consistency of the market inputs used for calibration.